services:
  web:
    build: .
    container_name: flask_ads_api
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    container_name: flask_ads_postgres
    restart: always

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    
    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: